function specs = MT03()
    %Marktech  MT03-004
    PHOTODIODE_RESPONSIVITY = 0.62; %Grabbed from plot...
    PHOTODIODE_CAPACITANCE = 25E-12;
    PHOTODIODE_RESISTANCE = 0.25; %Not spec'd;
    DARK_CURRENT = 1E-9;% 4nA
    specs = {PHOTODIODE_RESPONSIVITY, PHOTODIODE_CAPACITANCE, PHOTODIODE_RESISTANCE, DARK_CURRENT};
end
